# Generated by Django 6.0.2 on 2026-02-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='description_ja',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='hint_en',
            field=models.TextField(blank=True, null=True, verbose_name='Maslahat'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='hint_ja',
            field=models.TextField(blank=True, null=True, verbose_name='Maslahat'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='hint_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Maslahat'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='question_en',
            field=models.TextField(null=True, verbose_name='Savol'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='question_ja',
            field=models.TextField(null=True, verbose_name='Savol'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='question_uz',
            field=models.TextField(null=True, verbose_name='Savol'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Jumboq nomi'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='title_ja',
            field=models.CharField(max_length=200, null=True, verbose_name='Jumboq nomi'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Jumboq nomi'),
        ),
        migrations.AddField(
            model_name='room',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='room',
            name='description_ja',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='room',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='room',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Xona nomi'),
        ),
        migrations.AddField(
            model_name='room',
            name='title_ja',
            field=models.CharField(max_length=200, null=True, verbose_name='Xona nomi'),
        ),
        migrations.AddField(
            model_name='room',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Xona nomi'),
        ),
    ]
