# Generated by Django 6.0.2 on 2026-02-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_puzzle_description_en_puzzle_description_ja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='used_hint',
            field=models.BooleanField(default=False, verbose_name='Maslahat ishlatilgan'),
        ),
        migrations.AddField(
            model_name='userstatistics',
            name='hint_tokens',
            field=models.IntegerField(default=3, verbose_name='Maslahat tokenlari'),
        ),
        migrations.AddField(
            model_name='userstatistics',
            name='last_hint_refill',
            field=models.DateField(blank=True, null=True, verbose_name='Token yangilangan sana'),
        ),
    ]
