# Generated by Django 6.0.2 on 2026-02-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_userprogress_used_hint_userstatistics_hint_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='correct_answer_en',
            field=models.CharField(max_length=500, null=True, verbose_name="To'g'ri javob"),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='correct_answer_ja',
            field=models.CharField(max_length=500, null=True, verbose_name="To'g'ri javob"),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='correct_answer_uz',
            field=models.CharField(max_length=500, null=True, verbose_name="To'g'ri javob"),
        ),
    ]
